/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.FornecedorDAO;
import DAO.PecaDAO;
import DAO.UsuarioDAO;
import gestaopecas.Fornecedor;
import gestaopecas.Peca;
import gestaopecas.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cardo
 */
public class TelaListar extends javax.swing.JFrame {

    private String origem;

    /**
     * Creates new form TelaListar2
     */
    public TelaListar(String origem) {
        this.origem = origem; // Define a origem
        initComponents();

    }

    private TelaListar() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtAlterar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtVoltar = new javax.swing.JButton();
        jbtRelatorio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbListar = new javax.swing.JTable();
        jbtListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Listagem");

        jbtAlterar.setText("Alterar");

        jbtExcluir.setText("Excluir");

        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jbtRelatorio.setText("Relatório");

        jtbListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Senha", "Tipo Usuário"
            }
        ));
        jScrollPane2.setViewportView(jtbListar);

        jbtListar.setText("Listar");
        jbtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbtVoltar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jbtRelatorio)
                                .addGap(18, 18, 18)
                                .addComponent(jbtAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(jbtExcluir)
                                .addGap(29, 29, 29)
                                .addComponent(jbtListar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtVoltar)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtRelatorio)
                        .addComponent(jbtAlterar)
                        .addComponent(jbtExcluir)
                        .addComponent(jbtListar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarActionPerformed
        DefaultTableModel modelo;
        // Verifica a origem e configura as colunas correspondentes
        if ("usuario".equals(origem)) {
            modelo = new DefaultTableModel(
                    new Object[][]{}, // Dados inicialmente vazios
                    new String[]{"ID", "Nome", "Senha", "Tipo de Usuário"} // Cabeçalhos das colunas
            );

            jtbListar.setModel(modelo); // Define o modelo da tabela

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            List<Usuario> usuarios = usuarioDAO.getUsuarios();

            if (usuarios == null || usuarios.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não há usuários cadastrados no sistema.");
                return;
            }

            for (Usuario usuario : usuarios) {
                modelo.addRow(new Object[]{
                    usuario.getId(),
                    usuario.getNome(),
                    usuario.getSenha(),
                    usuario.isTipo_usuario() ? "Admin" : "Funcionário"
                });
            }
        } else if ("peca".equals(origem)) {
            modelo = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{"Código", "Nome", "Quantidade", "Preço"}
            );

            jtbListar.setModel(modelo);

            PecaDAO pecaDAO = new PecaDAO();
            List<Peca> pecas = pecaDAO.getPecas();

            if (pecas == null || pecas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não há peças cadastradas no sistema.");
                return;
            }

            for (Peca peca : pecas) {
                modelo.addRow(new Object[]{
                    peca.getCod(),
                    peca.getNome(),
                    peca.getQntdEstoque(),
                    peca.getPreco()
                });
            }
        } else if ("fornecedor".equals(origem)) {
            modelo = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{"ID", "Nome", "CNPJ/CPF", "Telefone", "Email", "Endereço"}
            );

            jtbListar.setModel(modelo);

            FornecedorDAO fornecedorDAO = new FornecedorDAO();
            List<Fornecedor> fornecedores = fornecedorDAO.getFornecedores();

            if (fornecedores == null || fornecedores.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não há fornecedores cadastrados no sistema.");
                return;
            }

            for (Fornecedor fornecedor : fornecedores) {
                modelo.addRow(new Object[]{
                    fornecedor.getId(),
                    fornecedor.getNome(),
                    fornecedor.getCnpj_cpf(),
                    fornecedor.getTelefone(),
                    fornecedor.getEmail(),
                    fornecedor.getEndereco()
                });
            }
        }
    }//GEN-LAST:event_jbtListarActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_jbtVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtListar;
    private javax.swing.JButton jbtRelatorio;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JTable jtbListar;
    // End of variables declaration//GEN-END:variables
}
