CREATE SCHEMA DBGESTAOPECAS;

CREATE TABLE usuario(
ID INTEGER NOT NULL AUTO_INCREMENT,
nome VARCHAR(45),
senha VARCHAR(255),
perfil VARCHAR(3), 
PRIMARY KEY (id)
);

CREATE TABLE peca(
id INTEGER NOT NULL AUTO_INCREMENT,
codigo INTEGER,
nome VARCHAR (45),
qtdEstoque INTEGER,
preco DOUBLE,
PRIMARY KEY(id)
);

CREATE TABLE relatorio(
id INTEGER NOT NULL AUTO_INCREMENT,
dataInico DATE,
dataFim DATE,
PRIMARY KEY (id)
);

CREATE TABLE histMov(
tipoMovimentacao VARCHAR(30),
qtd INTEGER,
dataHora DATETIME);

CREATE TABLE fornecedor(
id INTEGER NOT NULL AUTO_INCREMENT,
nome VARCHAR(100),
contato VARCHAR(17),
endereco VARCHAR(255),
PRIMARY KEY (id)
);